#!/usr/bin/env python3

from sys import argv

def main(statistics):
    with open(statistics) as f:
        rules = False
        total_lines = 0
        total_length = 0
        for line in f:
            if rules:
                data = line.split(':', maxsplit=1)[1]
                total_lines += 1
                total_length += data.count('|') + data.count('&')
                if data.startswith('Default rule'):
                    print('Rule count: %d' % total_lines)
                    print('Average complexity: %f' % (total_length / total_lines))
                    break
            if line.startswith('Phenotype:'):
                rules = True

if __name__ == '__main__':
    if len(argv) > 1:
        for file in argv[1:]:
            main(file)
    else:
        exit('Usage: %s statistics.txt' % argv[0])
